mercury:
  token:
    expireMins: 20
  venus:
    url: http://10.0.0.1:8081/
    timeoutMillis: 300000

spring:
  logging:
    level:
      root: DEBUG
      org.springframework.core : FATAL
      org.springframework.beans: FATAL
      org.springframework.context: FATAL
      org.springframework.transaction: ERROR
      org.springframework.test: DEBUG
      org.springframework.web: DEBUG
      org.hibernate: ERROR


  datasource:
    url: jdbc:mysql://mercury.shuolingdeng.com:23306/test
    username: test
    password: siW-!8#X
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    user:
      database: 0
      host: mercury.shuolingdeng.com
      port: 26379
      password: siW-!8#X
    token:
      database: 1
      host: mercury.shuolingdeng.com
      port: 26379
      password: siW-!8#X

  jackson:
    serialization:
      write-dates-as-timestamps: false

debug: true